language: node_js
node_js: 8.9.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export PATH=$HOME/.yarn/bin:$PATH
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
script: yarn build && yarn test && yarn e2e
sudo: false
git:
  depth: 3
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
